### ISSUE TITLE
Add to context menu for filename in panel "Rename file"

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#14]
Add to context menu for filename in panel

- Rename file

Copy the file itself to the clipboard so that you can paste it in the project manager panel to another folder.

**Comment by Chris2011** [comment]
Why did you close it as completed? This function was not implemented

**Comment by korenevskiy** [comment]
I doubt. It seems to me that this is a useful feature, but it duplicates the functionality of the project tree panel.
