### ISSUE TITLE
Reduce the horizontal indentation.

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#16]
Thank you. I installed the latest version 1.4.0. It has become much better. But I think the path buttons are still dispersed. Reduce the internal horizontal indentation inside the buttons by 2 times. So that the bul path is a little more merged.
More text will fit, and the path will be better readable.
Thank you for your hard work

**Comment by Chris2011** [comment]
You mean the horizontal padding inside the button is to much?

**Comment by korenevskiy** [comment]
> You mean the horizontal padding inside the button is to high?

Horizontal padding inside the button is to very width.

**Comment by Chris2011** [comment]
ok, will have a look into it. Thx.

**Comment by korenevskiy** [comment]
Reduce horizontal padding by 2x or 3x times

**Comment by Chris2011** [comment]
Lets see whats fits best

**Comment by Chris2011** [comment]
Done in release [1.5.0](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/tag/1.5.0)
