### ISSUE TITLE
Please add NBM file.

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#4]

**Comment by Chris2011** [comment]
Hi, thx for your ticket. It was intented to be not having an NBM becuase there is one big blogger and everyone should build this by there own and maybe have a look what can we make better here: #1

**Comment by korenevskiy** [comment]
But I'm not a Java programmer. I am a programmer in PHP, Javascript.

**Comment by Chris2011** [comment]
In the next days I can create an NBM file, but be aware you will not use it, because of preloading all folders and subfolders, it tooks really long time to open a file.

**Comment by korenevskiy** [comment]
Maybe you are 100% right. But let's figure it out. I was actually looking for a plugin to just view the folder path. I didn't even know it was more than that. I basically couldn't find out about it. VS Code I have little experience, and I don't remember how it looks in it. So first, post a screenshot of the plugin's appearance and write a little more description.

After all, I and other people only see the names of the plugin, and everyone has something special fantasizing about the plugin.

**Comment by Chris2011** [comment]
Sure, you are right. Probably I will have time on the weekend :). Thx for interest.

**Comment by korenevskiy** [comment]
Does downloading directories take 1 time or is it constantly done throughout the work? In some cases, maybe I would be satisfied that the Editor loads for a long time. When I get to work, I launch the editor and go for a coffee break, when I come the program is loaded. But I don't even know what kind of plugin it is. If you make an asynchronous plugin for six months on some weekends. Then maybe it would be useful for a small part of people to have at least a plugin file in the form that it is now at the moment.

**Comment by Chris2011** [comment]
It is just when you open the file and switchting between files, because it loads all folders and subfolders at once from the opening file. My idea is to just load nothing, but when you click on one folder but I couldn't handle it in the first place.

**Comment by Chris2011** [comment]
Nevermind, I will update the readme with a screenshot/screen capture and add the NBM file soon.

**Comment by Chris2011** [comment]
Here it is: https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/tag/1.0.0 sry for the delay.

**Comment by Chris2011** [comment]
Updated Readme will come later.

**Comment by Chris2011** [comment]
@korenevskiy I released version [1.1.0](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/download/1.1.0/netbeans-breadcrumb-explorer-1.1.0.nbm) which has better performance. Please test it and give feedback :)

**Comment by korenevskiy** [comment]
> @korenevskiy I released version [1.1.0](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/download/1.1.0/netbeans-breadcrumb-explorer-1.1.0.nbm) which has better performance. Please test it and give feedback :)

I can't install it. I drag the extension file into the modules window with the mouse. Then the installation starts, the window is minimized to the background installation. And ?! , the installation lasts indefinitely.

**Comment by korenevskiy** [comment]
But when the program is restarted. Reinstalling informs you that the extension has already been installed.

**Comment by korenevskiy** [comment]
The extension is still working. You can select other parent folders. Thanks

**Comment by korenevskiy** [comment]
@Chris2011 
I want to give feedback.
Your plugin is very beautiful.
1. I want to suggest removing folder icons in the panel. Displaying folders is very nice, but not practical. It takes up space, and it would be worse to read if there were no folder icons.
2. Add the copy path button relative to the root folder of the project.
3. It would also be convenient to copy the path only to the folder where you click copy path.

I also want to thank you for displaying icons in the drop-down menu of the list of files and folders. But in the panel itself, you can leave only the very first icon with the image of the file type, in the panel, folder icons interfere with work.

it would also be convenient if this path could be used as a separate control.
so that, by choice, it could be placed anywhere in the editor.

**Comment by Chris2011** [comment]
Hey, those are 3 different things (feature requests) for this plugin. Please create 3 (or more) separete tickets inside the bug tracker. Also they don't have anything in common so those are 3 separated (or more) tickets. This ticket here was just about missing nbm file and just giving you a reminder of a new version. If there is also smth to discuss, we can use the discussion section. Thx.
