### ISSUE TITLE
I want to suggest removing folder icons in the panel.

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#5]
I want to suggest removing folder icons in the panel. Displaying folders is very nice, but not practical. It takes up space, and it would be worse to read if there were no folder icons.
Even on Windows OS, there are no folder icons in Explorer next to each folder in the address bar.

Example: Explorer WIndows 11
![изображение](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/assets/6898474/1852082b-3083-4a26-a979-ab8be64569fd)
do the same as the explorer, there are icons in the drop-down list, but they are not in the row. Except for the file type icon.

**Comment by Chris2011** [comment]
Thx for the ticket, I will do it but with an option. Default will be without icons, just the first one and we can change it. Because at the moment I like the folders, but you are right, it could be distracting and also take space.

**Comment by korenevskiy** [comment]
format example:
`[icon folder]  Project > folder > subfolder > subsubfoldr > file.txt [icon file]`

**Comment by Chris2011** [comment]
Thx for your example.

**Comment by korenevskiy** [comment]
@Chris2011  Please tell me the address of the ISSUE forum for NetBeans.

**Comment by Chris2011** [comment]
The repo of NetBeans is hosted on GitHub too. Just search NetBeans und you will find it. It is part of Apache.

**Comment by Chris2011** [comment]
Done in 1.2.0.
