### ISSUE TITLE
Add the copy path button relative to the root folder of the project.

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#6]
Add the copy path button relative to the root folder of the project.

Either in the context menu or click on the ">" icon separating the folder names in the address bar so that you can copy the path of this folder relative to the root directory of the project to the clipboard. For example:
The project is located at: `D:/work/projects/ThisProject/subfolder/subsubfolder/favicon.ico`
The path should be copied:
to `subfolder/subsubfolder/favicon.ico`

It is convenient to copy the path to only one of the folders of the address bar path.
for example
 `subfolder > subsubfolder > favicon.ico`
 By hovering the mouse over the ">" icon, the icon turns into a clipboard icon, clicking on which copies the path to the clipboard, or part of the path, depending on where you clicked on this symbol icon.

**Comment by Chris2011** [comment]
Handy feature, thx. I dunno whether we should use the relative path instead of the absolute one. If you right click on an open editor you see the menu item "copy file path" which will be the absolte path with `Drive:\path\to\the\file.txt` this is why I struggle to make the right decision.

Can you please explain me, why the use case to copy the relative path is better than the absolute one? Where do you just need the relative path instead the absolute one?

Also another question: The file don't have any appended icon so this will be not possible to copy the file path 🤔

**Comment by korenevskiy** [comment]
All my projects are web applications.
thus, all files of the web application must be relative.
Embedding in JS, CSS, IMAGE templates are relative.
In addition, PHP program files are also written with relative paths. The fact is that the synchronized file on the linux server has a completely different path than the same file in the project folder, For this, using the framework, I can use the constant of the absolute location of the root directory with the address of the relative path. This will allow me to have web applications, easily archive, clone, and make backups, and also conduct local development without worrying that the paths do not match.
In addition, I have a lot, a lot of projects from different companies on my local computer, they are all in different directories, in different places, on different disks, let's say there are several web projects on each disk. I always know that the same module in every project has the same path. When I work with projects, I don't even remember where this project is, and I don't know on which disk. It's distracting.

format example:
`[icon folder] > Project > folder > subfolder > subsubfoldr > file.txt [icon file]`

Perhaps by copying the path from the first element (project name), the absolute path of the project folder is copied.
And if you copy the path of child subfolders, then the relative path from the root folder of the project will be copied.
The main thing is that when copying a relative path, so that there is no name of the project folder in this path, only the folders contained in the project.

**Comment by korenevskiy** [comment]
@Chris2011 
When I wrote programs in C#, everything works automatically in every project. There is no point in working with file paths in this language. Maybe only 2 paths are specified in the entire program and no more.

But when developing web applications in PHP, the project has to register 100-200 paths in different files. And this is repeated for each new project. Each new project is done once a month.
You have to spend a lot of time removing part of the path from the address, and replacing the slashes with the opposite ones.

**Comment by Chris2011** [comment]
I think I will add an extra menu on the chevron to choose relative or absolute path and also open folder in system for example

**Comment by korenevskiy** [comment]
> I think I will add an extra menu on the chevron to choose relative or absolute path and also open folder in system for example. give me some time.

Thank you very much. Please also make it possible to copy using slashes similar to those in the address bar of the Chrome Internet browser.
In Windows, slashes are used in the opposite direction. If the path with the path for Windows Explorer is copied, this path will not work for web applications.

Thank you very much. it will be a good extension.

**Comment by korenevskiy** [comment]
What do you think about creating 2 buttons to copy the path.
as well as adding a button to insert a path.
For example, if we insert a path, then your extension will check whether it is relative or absolute, and then apply it. ignoring the direction of the slashes.
In this case, you will not need to create a settings panel.

**Comment by Chris2011** [comment]
I will just use copy function from system or from NetBeans and the path depends on the system. I don't know what your use case is due to a lot of use cases. If we see that relative paths like /smth is so common, I will just use this one, but it really depends on the system. In Windows it is common C:\...\... yes you can use /this/path/too. I will not add an extra context menu for paste anything.

Fun fact, if you right click on the editor tab and choose copy file path it will use the absolute path which will be a system thing.
So my decision is just to add a popup menu to the chevron and see how it works. I don't need to create a settings panel yet. If you click on a folder, it will open the path as it is now, if you click on the chevron it will open a new menu with "Copy absolute file path" and "copy relative file path" items

**Comment by korenevskiy** [comment]
I understand that it is possible to copy the path as in the system. But the path for web applications has a slash in the opposite direction than Windows. Make the settings. And in general, you do not need to make a context menu. Just place 2-3 additional buttons on the panel. next to the file name.

**Comment by Chris2011** [comment]
Two extra buttons will not work, how should they look? You suggested to remove the folder icon already. Adding two new buttons will mess this stuff up. The chevron is still part of it and not used anyhow. Now it has a usage. Also I didn't say anything about a settings panel for this ticket here.

**Comment by korenevskiy** [comment]
before offering icons for copy buttons. I would suggest the option that a single button copies the path only in web format.
or an option like this. folder separation buttons that look like arrows can be copied in web format. And the very first button in the form of a folder copies the path as in the system.
Or it may be that your extension monitors the type of project (or monitors the type of program file) and copies the path, depending on this. If it is CSS,JS,JS,TS, PHP, then the path is copied with slashes "/", if not, then it is copied as in the system.

**Comment by Chris2011** [comment]
Option was not part of your ticket here. Also I don't want to have a button withing the menu for the folders. It is still for the folders/files, for nothing else.

So this is what I would like to achieve, it will fit maybe not 100% of your request but it could fit in both cases here:
1. Add a new popup menu separated from the submenu, when you click on the chevron.
2. Popup from the chevron will have 3 menuItems (Copy absolute path, copy relative path (web friendly), open folder in system (which also came into my mind but has nothing todo with your request, maybe I will create another ticket for this one)).

I will not add an option/setting for this ticket here to change anything. I will also not use any heuristic to check which path would be good. Also relative paths in Java/Maven for the resources folder is also usable. So I respect your case but I will add as good as possible to fit a lot of cases. Yours is just one. And I will also not add a new button into the submenu popup menu.

**Comment by korenevskiy** [comment]
“thanks. I'll be looking forward to it.

**Comment by Chris2011** [comment]
@korenevskiy fixed in [1.3.0](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/tag/1.3.0) Please test it and give feedback in the created discussion, thx.

**Comment by korenevskiy** [comment]
Thanks, I installed it. It looks beautiful. And very convenient. Thank you.
When I test, a list of subfolders and files is displayed there. When I hover the mouse over a subfolder, it also displays a list of subfolders, and when I hover over one of the subfolders, a list of subfolders is also displayed. If I have 2000 files in my project and 30-40 files are open in tabs. Does such a tree of subfolders on the panel take up a lot of RAM?
Will there be buttons for copying relative and absolute paths in a future version? Maybe try for the relative and absolute path copy menu items to place this in the new hamburger button and place this button on our panel?
Thank you. I'm already using the plugin. Very convenient.

**Comment by korenevskiy** [comment]
Thanks, I installed it. It looks beautiful. And very convenient. Thank you.
When I test, a list of subfolders and files is displayed there. When I hover the mouse over a subfolder, it also displays a list of subfolders, and when I hover over one of the subfolders, a list of subfolders is also displayed. If I have 2000 files in my project and 30-40 files are open in tabs. Does such a tree of subfolders on the panel take up a lot of RAM?
. . .
The folder separation sign works great. 
But, we cannot copy the relative and absolute paths for an open file.
We know that if you click on the file name, nothing happens. Let's make it so that if you click on the file name, the context menu will also open exactly the same. But with the difference that the path will be copied with the file name.

**Comment by korenevskiy** [comment]
There is also a suggestion to add the following items to the context menu of the file:
-  Copy the file (Copy the file itself)
- Rename the file.

But I have a fear I'm afraid to suggest to suggest to you that for this reason, you won't add the previous context menu suggestion to the file.

**Comment by korenevskiy** [comment]
My display is fine, But maybe there may be a problem that the path to the panel may not fit. Can you remove the indentation between the buttons?

**Comment by korenevskiy** [comment]
It can also remove the indentation in front of the top of the buttons and at the bottom of the buttons.

**Comment by Chris2011** [comment]
And also we can first discuss stuff in the discussion section of the release.
