### ISSUE TITLE
Add new context menu for filename for the same actions as for folders

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#9]
1. We know that if you click on the file name, nothing happens. Let's make it so that if you click on the file name, the context menu will also open exactly the same. But with the difference that the path will be copied with the file name.

2. There is also a suggestion to add the following items to the context menu of the file:

- Copy the file (Copy the file itself)
- Rename the file

3. My view is fine, But maybe there may be a problem that the path to the panel may not fit. Can you remove the indentation between the buttons?
It can also remove the indentation in front of the top of the buttons and at the bottom of the buttons. to make the panel a little narrower

**Comment by Chris2011** [comment]
> We know that if you click on the file name, nothing happens. Let's make it so that if you click on the file name, the context menu will also open exactly the same. But with the difference that the path will be copied with the file name.

If I understand the last sentence correct, you want to automatically copy the filename by clicking on it while it opens the context menu? If yes, this is kinda hidden magic and I'm against it. I will add the same functionality to such a context menu like for the seperator context menu like: Copy absolute path, copy relative path, open containing folder.

> There is also a suggestion to add the following items to the context menu of the file:

> Copy the file (Copy the file itself)
> Rename the file

This is also another feature requst. Please create a ticket for each action that you want and describe it more precise. For action one copy file you mean the whole file content?

Rename file is more complex so I will not cover it here again it is a new feature and will be covered in a new ticket.

> My view is fine, But maybe there may be a problem that the path to the panel may not fit. Can you remove the indentation between the buttons?
It can also remove the indentation in front of the top of the buttons and at the bottom of the buttons. to make the panel a little narrower

Again please don't cover diferent things which are independent from each other in one ticket. One ticket should do one thing. We don't have stories or a project here where we can add tasks. Yes we can, but I don't want to change the to a project here. This is also more a thing to discuss. Unfortunately I don't know exactly what you mean. My intention was to make a good UX to handle click events with a good click view. I don't know what you mean with view. So please change this ticket to just the context menu for the file for the common actions. Thx.

**Comment by korenevskiy** [comment]
> If I understand the last sentence correct, you want to automatically copy the filename by clicking on it while it opens the context menu? If yes, this is kinda hidden magic and I'm against it. I will add the same functionality to such a context menu like for the seperator context menu like: Copy absolute path, copy relative path, open containing folder.

I want that when clicking on the file name, the context menu opens in the same way as on the separator, with exactly the same menu items.

For example, when clicking on the file name, we will see:
- Copy absolute path
- Copy relative path
- Open containing folder 

By clicking on the `Copy absolute Path` we will get: 

- S:\sites\work_site\plugin\index.php

By clicking on the `Copy relative Path` we will get: 

- /plugin/index.php




> So please change this ticket to just the context menu for the file for the common actions. Thx.

Excuse me

**Comment by Chris2011** [comment]
Done in latest release: [1.4.0](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/tag/1.4.0)
